[project]
name = "scripts"
version = "0.1.0"
description = "Nautilus BCI Toolkit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "matplotlib>=3.11.0",
    "numpy>=2.5.0",
    "pylsl>=1.18.2",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.1",
    "scipy>=1.18.0",
    "mne>=1.12.1",
    "mne-bids>=0.19.0",
    "pybv>=0.8.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "pyriemann>=0.12",
    "torch>=2.13.0",
]

[project.optional-dependencies]
hardware = [
    "pygds",
    "gpype>=0.1.0",
]

[tool.uv.sources]
pygds = { path = "wheels/pygds-1.24.0-py3-none-any.whl" }

