function classifier = loadIntendiXClassifier(from) 
    try
        doc = xmlread(from);
        root = doc.getDocumentElement();
        
    catch ME
        error('Failed to load classifier file ''%s''',from);
    end
    if ~strcmp(char(root.getTagName()),'P300Classifier') 
        error('File ''%s'' does not describe a valid P300 classifier generated by c# ClassificationToolBox');
    end
    core = root.getElementsByTagName('Includes');
    if core.getLength() < 1
        default = doc.createElement('Includes');
        default.appendChild(doc.createTextNode('LDAClassifier'));
        root.insertBefore(root.getFirstChild(),default);
        core = root.getElementsByTagName('Includes');
    end
    classifier = struct();
    for include = 0:core.getLength()-1
        try 
            core = char(core.item(include).getChildNodes().item(0).getNodeValue());
        catch ME
            error('Not a classifier generated by c# classification tool box');
        end
        switch core
            case 'LDAClassifier'
                classifier.methodName = 'Linear Discriminant Analysis';
                classifier.abreviation = 'MLDA';
                classifier.F=struct();
                classifier.F.bias = parseVectors(root,'Bias',1,2);                
                classifier.numClasses = 2;
                classifier.F.weight = parseVectors(root,'WeightVector',2)';
            otherwise
                continue;
        end
    end
    classifier.Stats = struct();
    classifier.Stats.Accuracy = parseVectors(root,'Accuracy',1);
    classifier.Stats.NumFlashes = length(classifier.Stats.Accuracy);
    classifier.Stats.MinSelect = parseVectors(root,'MinSelectProbability',1,classifier.Stats.NumFlashes);
    classifier.Stats.NOptFl = parseVectors(root,'MinFlashesForMaxAccuracy',1,1);
    classifier.Stats.EstMaxFl = parseVectors(root,'MaxFlashesForMaxAccuracy',1,1);
    classifier.Stats.Confidence = parseVectors(root,'ConfidenceInterval',1,2);
    classifier.Stats.ConfidenceTable = parseVectors(root,'LimitMapBoundaries',1);
    classifier.Stats.ConfidenceTable(2,:) = parseVectors(root,'LimitMapMinFlashes',1,size(classifier.Stats.ConfidenceTable,2));
    classifier.Stats.ConfidenceTable(3,:) = parseVectors(root,'LimitMapMaxFlashes',1,size(classifier.Stats.ConfidenceTable,2));
end
    
function content = parseVectors(root,nodename,count,elemcount)
    toload = root.getElementsByTagName(nodename);
    if toload.getLength() ~= count
        error('loadIntendiXClassifier:parse','File does not conatin any ''%s'' entry, assuming not a valid intendix Classifier',nodename);
    end
    if ( nargin > 3 )
        if    ~isscalar(elemcount) ...
           || ~isnumeric(elemcount) ...
           || ( elemcount < 1 ) ...
           || ( floor(elemcount) ~= elemcount )
            error('loadIntendiXClassifier:parse','Invalid value specified for elemcount');
        end        
        content = zeros(count,elemcount);
        nextentry = 1;
    else
        textvalue = toload.item(0).getChildNodes();
        if textvalue.getLength() < 1
            error('loadIntendiXClassifier:parse','Node ''%s'' is empty',nodename);
        end
        tokens = regexp(char(textvalue.item(0).getNodeValue()),'([+-]?\d+(?:\.\d+)?)(?:;|$)','tokens');
        if    isempty(tokens)
            error('loadIntendiXClassifier:parse','Node ''%s'' does not contain any numeric data',nodename);
        end
        content = str2double([tokens{:}]);
        elemcount = length(content);
        content(end+1:count,:) = 0;
        nextentry = 2;
    end
    for collect = nextentry:toload.getLength()
        textvalue = toload.item(collect-1).getChildNodes();
        if textvalue.getLength() < 1
            error('loadIntendiXClassifier:parse','Repetition #%d of node ''%s'' is empty',collect,nodename);
        end
        tokens = regexp(char(textvalue.item(0).getNodeValue()),'([+-]?\d+(?:\.\d+)?)(?:;|$)','tokens');
        if    isempty(tokens) ...
           || ( length( [tokens{:}] ) ~= elemcount ) 
            error('loadIntendiXClassifier:parse','Repetion #%d of node ''%s'' does not contain requested number (%d) of numeric values',collect,nodename,elemcount);
        end
        content(collect,:) = str2double([tokens{:}]);
    end 
end